### ISSUE TITLE
not add-migration work

### ISSUE THREAD

**Issue by mbasij1** [simpleidserver/EFCore.Cassandra#18]
I Created New Project And Config Project, instead of ef core3.1, I added ef core 5 and the below exception appears:

add-migration init
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.SemanticVersionComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(IOperationReportHandler reportHandler, IDictionary args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language, String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.

**Comment by simpleidserver** [comment]
Hi,

The project "EFCore.Cassandra" is using "Microsoft.EntityFrameworkCore" version "3.1.4",  therefore the version "5.0.1" cannot be included in your project.

**Comment by C0ffeeCode** [comment]
Do you plan on updating this DB provider to support EF Core 5 in the near future?

**Comment by simpleidserver** [comment]
EF Core 5 will be supported in the next release (version 3.0.0), it will be published in February.

**Comment by C0ffeeCode** [comment]
Does that mean it's now compatible with EF Core 5?

**Comment by simpleidserver** [comment]
The project has been migrated to NET5.0. 
please refer to the branch "origin/release/3.0.0"
